document.querySelector('.menu-toggle').addEventListener('click',function(){const open=this.getAttribute('aria-expanded')!=='true';this.setAttribute('aria-expanded',String(open));this.setAttribute('aria-label',open?'Close menu':'Open menu');document.querySelector('#navigation').classList.toggle('open',open)});
document.querySelectorAll('#navigation a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#navigation').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');document.querySelector('.menu-toggle').setAttribute('aria-label','Open menu')}));
const htmlEscape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const courses=ZeeStore.read().courses.filter(c=>c.published&&!c.archived).map(c=>Object.fromEntries(Object.entries(c).map(([k,v])=>[k,typeof v==='string'?htmlEscape(v):Array.isArray(v)?v.map(htmlEscape):v])));
const money=n=>'₹'+n.toLocaleString('en-IN');
const courseContent=document.querySelector('#course-content');
courseContent.innerHTML=`<div class="course-filters" role="group" aria-label="Filter courses">${['All courses','Design & architecture','Marketing & AI','Media & content','Tech & Coding'].map((c,i)=>`<button class="filter ${i===0?'selected':''}" aria-pressed="${i===0}" data-filter="${c}">${c}${i===0?' <span>'+courses.length+'</span>':''}</button>`).join('')}</div><p id="course-count" class="sr-only" aria-live="polite"></p><div class="course-grid"></div><div class="course-help"><span>Not sure where to start? <strong>Let’s find your fit.</strong></span><a href="tel:+918863811365">Talk to a counsellor <span>↗</span></a></div>`;
function renderCourses(category='All courses'){const filtered=courses.filter(c=>category==='All courses'||c.category===category);document.querySelector('.course-grid').innerHTML=filtered.map(c=>`<article class="course-card"><button class="course-image" data-detail="${c.id}" aria-label="Explore ${c.title}"><img src="assets/${c.image}" alt="${c.title}" loading="lazy" width="600" height="400"><span class="course-duration">${c.months}</span><span class="course-image-title">${c.tag}</span></button><div class="course-body"><span class="course-category">${c.category}</span><h3>${c.title}</h3><p>${c.skills.slice(0,3).join(' · ')}</p><div class="course-meta"><span>↗ Paid internship included</span><span>Online / Offline</span></div><div class="price-row"><div><strong>${money(c.price)}</strong> ${c.original?`<s>${money(c.original)}</s>`:''}<small>Complete course fee</small></div><button class="course-arrow" data-detail="${c.id}" aria-label="View ${c.title} details">↗</button></div><button class="enroll-card" data-enroll="${c.id}">Enroll now <span>→</span></button></div></article>`).join('');document.querySelector('#course-count').textContent=filtered.length+' courses shown';}
renderCourses();
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(a=>{a.classList.remove('selected');a.setAttribute('aria-pressed','false')});b.classList.add('selected');b.setAttribute('aria-pressed','true');renderCourses(b.dataset.filter)}));
document.querySelector('#more-content').innerHTML=`
<section class="internship section" id="internship"><div class="internship-intro"><span class="eyebrow">02 / 100% GUARANTEED PAID INTERNSHIP</span><h2>Your first experience.<br>Your first <span class="serif">paycheck.</span></h2><p>Learning is only the beginning. Complete any course and put your skills to work with a guaranteed 3-month paid internship with our hiring & corporate partners.</p><a class="button primary" href="#courses">Start with a skill <span>↗</span></a></div><div class="internship-offer"><div class="offer-top"><span>ZEE ACADEMY × BETHEBESTCODER</span><span>↗</span></div><strong>100<span>%</span></strong><h3>Guaranteed Paid Internship</h3><div class="offer-stats"><div><b>3 months</b><span>100% Confirmation for every student</span></div><div><b>₹8,000–₹12,000</b><span>Stipend per month</span></div></div><p>Every course. Every student. 100% internship confirmation for 3 months.</p></div><div class="journey"><div><span>01</span><h3>Learn</h3><p>Build your foundation with industry skills.</p></div><div><span>02</span><h3>Practice</h3><p>Live projects & case studies.</p></div><div><span>03</span><h3>Implement</h3><p>Bring your skills to the workplace.</p></div><div><span>04</span><h3>Grow</h3><p>Build your portfolio & career.</p></div></div></section>
<section class="section why" id="why-us"><div class="section-head"><div><span class="eyebrow">03 / WHY CHOOSE ZEE ACADEMY?</span><h2>Less just watching.<br>More <span class="serif">actually doing.</span></h2></div><p>100% Practical & Industry-Oriented Courses in Tech, Design, Marketing & AI.<br>Real skills taught live by industry practitioners.</p></div><div class="benefit-grid"><article><span>01 / PRACTICAL & INDUSTRY-ORIENTED</span><h3>100% Practical Learning</h3><p>Industry-oriented courses, live projects and real case studies that turn concepts into skills you can use immediately.</p></article><article><span>02 / LEARN FROM EXPERTS</span><h3>Guidance from Top Engineers</h3><p>Learn directly from software engineers and specialists at Deloitte, Capgemini, and ByteBix.</p></article><article><span>03 / CAREER & PERSONALITY</span><h3>Placement & Referral Support</h3><p>Personality development sessions, resume reviews, 1-on-1 code reviews, and direct hiring referrals.</p></article><article><span>04 / YOUR LIFE, YOUR PACE</span><h3>Flexible Online & Offline Batches</h3><p>Flexible schedules online or at our Patna centre, followed by a guaranteed 3-month paid internship.</p></article></div><div class="who"><div><span class="eyebrow">WHO CAN JOIN?</span><h3>Ambition is the <br>best starting point.</h3></div><div class="audience-tags">${['Students','Graduates','MBA Aspirants','Entrepreneurs','Working Professionals','Business Owners','Freelancers','Anyone who wants to build a successful career'].map(t=>`<span>${t}</span>`).join('')}</div></div></section>
<section class="section mentors" id="mentors"><div class="section-head"><div><span class="eyebrow">04 / ZEE ACADEMY DESIGN & CREATIVE FACULTY</span><h2>Meet your <span class="serif">craft mentors.</span></h2></div><p>People who bring their design, media, and marketing craft to the classroom.<br>And bring out the best in you.</p></div><div class="mentor-grid">
<article><div class="mentor-image"><img src="assets/shivani.png" alt="Shivani, AutoCAD faculty" loading="lazy" width="1121" height="1403"><span>AUTOCAD & DRAFTING</span></div><div class="mentor-heading"><h3>Shivani</h3><span>01</span></div><p>AutoCAD & Design faculty</p><p class="mentor-desc">From a first line to a precise plan. Learn the foundations of professional drafting and architectural documentation.</p></article>
<article><div class="mentor-image"><img src="assets/paritosh.png" alt="Paritosh, Media course faculty" loading="lazy" width="877" height="992"><span>MEDIA & CONTENT</span></div><div class="mentor-heading"><h3>Paritosh</h3><span>02</span></div><p>Media & Content faculty</p><p class="mentor-desc">Find your story and master the craft of storytelling, camera work, editing, and audience building.</p></article>
<article><div class="mentor-image"><img src="assets/ratnesh.png" alt="Ratnesh, Digital Marketing and Interior Design faculty" loading="lazy" width="1023" height="1537"><span>MARKETING & DESIGN</span></div><div class="mentor-heading"><h3>Ratnesh</h3><span>03</span></div><p>Digital Marketing & Interior Design</p><p class="mentor-desc">Faculty and motivational speaker, helping you connect creativity, design, and growth with your next career move.</p></article>
</div></section>
<section class="section tech-mentors" id="tech-mentors"><div class="section-head"><div><span class="eyebrow">05 / BETHEBESTCODER IT & SOFTWARE FACULTY</span><h2>The people who’ll <span class="serif">review your code.</span></h2></div><p>Every IT course is taught live by engineers who write code at work every day.<br>Deloitte · ByteBix · Ex-Capgemini</p></div><div class="mentor-grid">
<article><div class="mentor-image"><img src="https://res.cloudinary.com/ddam1v1kr/image/upload/f_auto,q_auto,w_600/v1786498497/mentor-ashish-kumar-jha_tztics.webp" alt="Ashish Kumar Jha, Senior Consultant at Deloitte" loading="lazy" width="600" height="750"><span>DELOITTE · FULL-STACK</span></div><div class="mentor-heading"><h3>Ashish Kumar Jha</h3><span>01</span></div><p>Senior Consultant · Full-Stack & BFSI</p><p class="mentor-desc">Builds enterprise banking systems for Fortune 500 clients. 6+ years across Tata, Cognizant and Deloitte. Teaches the exact stack he uses at work every day.</p></article>
<article><div class="mentor-image"><img src="https://res.cloudinary.com/ddam1v1kr/image/upload/f_auto,q_auto,w_600/v1786498497/mentor-murlidhar-pathak_q4uxbv.webp" alt="Murlidhar Pathak, Data Scientist at ByteBix Technologies" loading="lazy" width="600" height="750"><span>BYTEBIX · DATA SCIENTIST</span></div><div class="mentor-heading"><h3>Murlidhar Pathak</h3><span>02</span></div><p>Data Scientist · Machine Learning</p><p class="mentor-desc">Four years across mobile apps and full stack, now building ML systems for live client products. Teaches Python, AI, and production deployment.</p></article>
<article><div class="mentor-image"><img src="https://res.cloudinary.com/ddam1v1kr/image/upload/f_auto,q_auto,w_600/v1786498497/mentor-bhavani_ghnqrn.webp" alt="Bhavani Kumari, Senior Software Engineer Ex-Capgemini" loading="lazy" width="600" height="750"><span>EX-CAPGEMINI · QA & JAVA</span></div><div class="mentor-heading"><h3>Bhavani Kumari</h3><span>03</span></div><p>Senior Software Engineer · QA Automation</p><p class="mentor-desc">Two years at Capgemini writing Java and automating test suites in Selenium. Helps learners clear the exact jump into top tech roles.</p></article>
</div></section>
<section class="section faq" id="faq"><div><span class="eyebrow">06 / A LITTLE MORE CLARITY</span><h2>Good <span class="serif">questions.</span><br>Straight answers.</h2><p>Still curious? <a href="tel:+918863811365">Let’s talk ↗</a></p></div><div class="faq-list"><details><summary>Do I need experience to join?</summary><p>Our programs welcome students, graduates, MBA aspirants, professionals, entrepreneurs and freelancers. Speak with our counsellor to choose a course that fits your background and goals.</p></details><details><summary>Can I study online or in person?</summary><p>We offer flexible online and offline batches. For in-person learning, visit our centre on Boring Patliputra Road, Patna. Contact us to confirm the next batch and timings for your course.</p></details><details><summary>How does the 100% paid internship work?</summary><p>After completing any course, Zee Academy provides a 100% guaranteed three-month paid internship, with a stipend of ₹8,000–₹12,000 per month. The admissions team will guide you on the assignment, start date and arrangements.</p></details><details><summary>What is included in the course fee?</summary><p>The displayed fee is for the complete course. Training includes 100% practical learning, live projects, personality development sessions, mentor guidance, and guaranteed paid internship opportunities.</p></details><details><summary>Can I pay and enroll on this website?</summary><p>You can try the complete demo enrollment flow. Payments are simulated: no money is charged and no real admission is created. To enroll for a real batch, contact Zee Academy directly.</p></details></div></section>
<section class="contact section" id="contact"><div class="contact-heading"><span class="eyebrow">SMALL FIRST STEP. BIG POSSIBILITIES.</span><h2>Your future is<br>waiting for <span class="serif">you.</span><span class="contact-star" aria-hidden="true">✳</span></h2><div><a class="button primary" href="#courses">Let’s get started <span>↗</span></a><a class="text-link" href="https://wa.me/918863811365" target="_blank" rel="noopener">Chat on WhatsApp ↗</a></div></div><div class="contact-info"><div><span>COME SAY HELLO</span><p>Usha Niketan, 2nd Floor<br>House No. 122, Boring Patliputra Road<br>Near Bank of Baroda, Patna</p><a href="https://www.google.com/maps/search/?api=1&query=Usha+Niketan+House+122+Boring+Patliputra+Road+Patna" target="_blank" rel="noopener">Get directions ↗</a></div><div><span>LET’S FIND YOUR NEXT STEP</span><a href="tel:+918863811365">+91 88638 11365</a><a href="tel:+919534900999">+91 95349 00999</a><p>Online & offline batches available</p></div></div></section>
<footer><a class="brand" href="#"><img class="academy-logo" src="assets/zee-academy-logo.png" alt="Zee Academy — Future maker" width="577" height="433"></a><p>© ${new Date().getFullYear()} Zee Academy. Built for your next chapter.</p><a href="#">Back to top ↑</a></footer>`;
const dialogRoot=document.querySelector('#dialog-root');
dialogRoot.innerHTML='<dialog id="course-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Close dialog">×</button><div id="dialog-content"></div></dialog>';
const dialog=document.querySelector('#course-dialog'),dialogContent=document.querySelector('#dialog-content');
let chosenCourse,student={},paymentTimer;
function openDialog(){if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');dialog.scrollTop=0;}
function closeDialog(){clearTimeout(paymentTimer);dialog.close();document.body.classList.remove('modal-open');}
document.querySelector('.dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('close',()=>{clearTimeout(paymentTimer);document.body.classList.remove('modal-open')});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
function detail(id){chosenCourse=courses.find(c=>c.id===id);if(!chosenCourse)return;const c=chosenCourse;dialogContent.innerHTML=`<span class="eyebrow">${c.category}</span><h2 id="dialog-title" tabindex="-1">${c.title}</h2><p class="dialog-desc">${c.description}</p><div class="detail-stats"><span>${c.months}</span><span>Online / Offline</span><span>${money(c.price)}</span></div><h3>What you’ll learn</h3><ul class="skill-list">${c.skills.map(s=>`<li>${s}</li>`).join('')}</ul><div class="detail-outcome"><span>YOUR NEXT STEP</span><p>${c.outcome}</p></div><p class="detail-faculty">Faculty: ${c.mentor}</p><p class="internship-detail">✓ 100% Guaranteed 3-month paid internship (₹8,000–₹12,000/mo) after course completion</p><button class="button primary full" data-enroll="${c.id}">Enroll in this course <span>↗</span></button><p class="demo-note">Enrollment is a demo. No payment will be collected.</p>`;openDialog();document.querySelector('#dialog-title').focus();}
function enrollment(id){chosenCourse=courses.find(c=>c.id===id);if(!chosenCourse)return;student={};showDetailsForm();}
function steps(n){return `<div class="steps"><span class="${n===1?'current':''}">01 Your details</span><span class="${n===2?'current':''}">02 Payment</span><span class="${n===3?'current':''}">03 You’re set</span></div>`;}
function showDetailsForm(){const c=chosenCourse;dialogContent.innerHTML=`<span class="demo-badge">DEMO ENROLLMENT</span>${steps(1)}<h2 id="dialog-title" tabindex="-1">Your next chapter.</h2><p class="dialog-desc">Start with ${c.title}.</p><div class="enroll-summary"><span>${c.title}<small>${c.months} · Paid internship included</small></span><strong>${money(c.price)}</strong></div><form id="enrollment-form"><label>Full name<input name="name" autocomplete="name" required minlength="2" maxlength="80" placeholder="Your full name"></label><div class="form-row"><label>Email address<input name="email" type="email" autocomplete="email" required maxlength="120" placeholder="you@example.com"></label><label>Mobile number<input name="phone" type="tel" autocomplete="tel-national" inputmode="tel" required pattern="[6-9][0-9]{9}" maxlength="10" placeholder="10-digit Indian number" title="Enter a 10-digit Indian mobile number starting with 6, 7, 8 or 9"></label></div><label>How would you like to learn?<select name="mode"><option>Offline · Patna centre</option><option>Online</option></select></label><label class="checkbox"><input type="checkbox" required> <span>I understand this is a demo. No real admission or payment will be made.</span></label><button class="button primary full" type="submit">Continue to payment <span>→</span></button></form><p class="demo-note">Use sample details. After demo payment, this course is added to student@gmail.com on this browser. Contact details are not saved.</p>`;openDialog();for(const [k,v] of Object.entries(student)){const field=document.querySelector(`[name="${k}"]`);if(field)field.value=v}document.querySelector('#enrollment-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;student=Object.fromEntries(new FormData(f));showPayment()});document.querySelector('#dialog-title').focus();}
function showPayment(){dialogContent.innerHTML=`<span class="demo-badge">TEST MODE · NO REAL CHARGE</span>${steps(2)}<h2 id="dialog-title" tabindex="-1">One step closer.</h2><p class="dialog-desc">Review your course and try a simulated payment.</p><div class="enroll-summary"><span>${chosenCourse.title}<small>${chosenCourse.months} · <span id="summary-mode"></span></small></span><strong>${money(chosenCourse.price)}</strong></div><div class="student-summary"><strong id="summary-name"></strong><span id="summary-email"></span></div><fieldset class="payment-methods"><legend>Choose a demo payment method</legend><label><input type="radio" name="method" value="UPI" checked><span>UPI<small>Simulated UPI payment</small></span><b>↗</b></label><label><input type="radio" name="method" value="Card"><span>Debit / Credit card<small>Test card · No card details needed</small></span><b>▤</b></label><label><input type="radio" name="method" value="Net banking"><span>Net banking<small>Simulated bank payment</small></span><b>⌂</b></label></fieldset><div class="payment-total"><span>Total demo amount</span><strong>${money(chosenCourse.price)}</strong></div><p class="payment-notice">This is a payment simulation. Do not enter any real card, bank or UPI details.</p><button class="button primary full" id="pay-button">Simulate payment · ${money(chosenCourse.price)} <span>→</span></button><div class="payment-controls"><button id="back-details">← Edit details</button><button id="fail-payment">Try a failed payment</button></div><p id="payment-status" role="status"></p>`;document.querySelector('#summary-mode').textContent=student.mode;document.querySelector('#summary-name').textContent=student.name;document.querySelector('#summary-email').textContent=student.email;document.querySelector('#back-details').onclick=showDetailsForm;document.querySelector('#fail-payment').onclick=()=>{document.querySelector('#payment-status').textContent='Demo payment declined. No money was charged. Try again or choose another method.'};document.querySelector('#pay-button').onclick=async()=>{const button=document.querySelector('#pay-button');button.disabled=true;button.textContent='Simulating payment…';document.querySelector('#fail-payment').disabled=true;document.querySelector('#back-details').disabled=true;document.querySelector('#payment-status').textContent='Processing a test payment. No money is being transferred.';const method=document.querySelector('[name="method"]:checked').value;paymentTimer=setTimeout(()=>showSuccess(method),1100)};dialog.scrollTop=0;document.querySelector('#dialog-title').focus();}
function showSuccess(method){const reference='ZEE-DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase();ZeeStore.enroll(chosenCourse.id,student.mode.startsWith('Offline')?'offline':'online');dialogContent.innerHTML=`<div class="success-icon">✓</div><span class="demo-badge">DEMO COMPLETE</span>${steps(3)}<h2 id="dialog-title" tabindex="-1">Your future looks bright.</h2><p class="dialog-desc">You’ve completed the enrollment demo.</p><div class="success-summary"><div><span>Course</span><strong>${chosenCourse.title}</strong></div><div><span>Learning mode</span><strong id="success-mode"></strong></div><div><span>Payment method</span><strong>${method} · Simulated</strong></div><div><span>Demo amount</span><strong>${money(chosenCourse.price)}</strong></div><div><span>Reference</span><strong>${reference}</strong></div></div><p class="payment-notice">Your course is ready in the demo student portal on this browser. No money was charged and no real admission or email was created.</p><a class="button primary full" href="lms.html?course=${chosenCourse.id}">Go to student portal <span>↗</span></a><p class="demo-note">Student login: student@gmail.com · Password: 123456</p><button class="button full" id="finish-demo">Keep exploring</button>`;document.querySelector('#success-mode').textContent=student.mode;document.querySelector('#finish-demo').onclick=closeDialog;dialog.scrollTop=0;document.querySelector('#dialog-title').focus();}
document.addEventListener('click',e=>{const detailButton=e.target.closest('[data-detail]'),enrollButton=e.target.closest('[data-enroll]');if(detailButton)detail(detailButton.dataset.detail);if(enrollButton)enrollment(enrollButton.dataset.enroll)});

// Subtle entry motion, with fully visible content when motion is reduced.
if ('IntersectionObserver' in window && !window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
 const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:.55,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:550,easing:'ease-out'});observer.unobserve(entry.target)}})},{threshold:.08});
 document.querySelectorAll('.internship-intro,.internship-offer,.benefit-grid article,.mentor-grid article').forEach(el=>observer.observe(el));
}
